package com.fintrack.controller;

import com.fintrack.entity.User;
import com.fintrack.service.AuthService;
import com.fintrack.service.NetWorthService;
import com.fintrack.service.RecurringService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Derived analytics: recurring-payment detection and net-worth history.
 * Split from InsightController because these are computed locally rather than
 * generated by the LLM.
 */
@RestController
@RequestMapping("/api")
@RequiredArgsConstructor
@Validated
@Tag(name = "Analytics", description = "Recurring payments and net worth")
@SecurityRequirement(name = "bearerAuth")
public class InsightsExtraController {

    private final RecurringService recurringService;
    private final NetWorthService netWorthService;
    private final AuthService authService;

    @GetMapping("/recurring")
    @Operation(summary = "Detect recurring expenses (subscriptions, bills) from transaction history")
    public ResponseEntity<List<RecurringService.RecurringItem>> recurring(Authentication auth) {
        User user = authService.getCurrentUser(auth.getName());
        return ResponseEntity.ok(recurringService.detect(user.getId()));
    }

    @GetMapping("/networth")
    @Operation(summary = "Net worth history from daily balance snapshots")
    public ResponseEntity<List<NetWorthService.NetWorthPoint>> netWorth(
            @RequestParam(defaultValue = "90") @Min(7) @Max(730) int days,
            Authentication auth) {
        User user = authService.getCurrentUser(auth.getName());
        return ResponseEntity.ok(netWorthService.getHistory(user.getId(), days));
    }
}
