import type React from 'react';

export const formInputFocus = { borderColor: 'rgba(99,102,241,0.6)', boxShadow: '0 0 0 3px rgba(99,102,241,0.12)' };
export const formInputBlur = { borderColor: 'var(--border-strong)', boxShadow: 'none' };

export const d: Record<string, React.CSSProperties> = {
  root: { display: 'flex', minHeight: '100vh', background: 'var(--bg)' },

  sidebar: {
    width: 236, background: 'var(--sidebar-bg)',
    borderRight: '1px solid var(--border)',
    display: 'flex', flexDirection: 'column',
    padding: '24px 0', position: 'sticky', top: 0, height: '100vh', flexShrink: 0,
  },
  sidebarTop: { flex: 1, padding: '0 14px' },
  logo: { display: 'flex', alignItems: 'center', gap: 10, padding: '4px 10px', marginBottom: 32 },
  logoIcon: {
    width: 34, height: 34, borderRadius: 9,
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  logoText: { fontSize: 17, fontWeight: 700, letterSpacing: '-0.3px', color: 'var(--text-1)' },
  nav: { display: 'flex', flexDirection: 'column', gap: 2 },
  navBtn: {
    display: 'flex', alignItems: 'center', gap: 10,
    padding: '10px 12px', borderRadius: 10, border: 'none',
    background: 'transparent', color: 'var(--text-3)',
    cursor: 'pointer', width: '100%', textAlign: 'left',
    fontSize: 14, fontWeight: 500, transition: 'all 0.15s', position: 'relative',
  },
  navBtnActive: { background: 'rgba(99,102,241,0.18)', color: '#c7d2fe' },
  aiBadge: {
    marginLeft: 'auto', fontSize: 10, fontWeight: 700,
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff', padding: '2px 6px', borderRadius: 4, letterSpacing: '0.05em',
  },
  sidebarFooter: {
    borderTop: '1px solid var(--border)', padding: '16px 14px 0',
    display: 'flex', alignItems: 'center', gap: 8,
  },
  userRow: { display: 'flex', alignItems: 'center', gap: 10, flex: 1, minWidth: 0 },
  avatar: {
    width: 34, height: 34, borderRadius: 10, flexShrink: 0,
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 14, fontWeight: 700, color: '#fff',
  },
  userInfo: { minWidth: 0 },
  userName: { fontSize: 13, fontWeight: 600, color: 'var(--text-1)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  userEmail: { fontSize: 11, color: 'var(--text-3)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  logoutBtn: { background: 'transparent', border: 'none', cursor: 'pointer', display: 'flex', padding: 6, borderRadius: 8, flexShrink: 0 },

  main: { flex: 1, padding: '32px 40px', overflowY: 'auto', minWidth: 0 },
  mainMobile: { padding: '16px 16px 96px' },
  mobileTopBar: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    marginBottom: 20,
  },
  mobileNav: {
    position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 300,
    display: 'flex', justifyContent: 'space-around',
    background: 'var(--surface-2)', borderTop: '1px solid var(--border)',
    padding: '8px 4px calc(8px + env(safe-area-inset-bottom))',
  },
  mobileNavBtn: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4,
    background: 'transparent', border: 'none', cursor: 'pointer',
    padding: '6px 10px', borderRadius: 10, minWidth: 56,
  },
  mobileNavLabel: { fontSize: 10, fontWeight: 600, letterSpacing: '0.01em' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 32, gap: 16, flexWrap: 'wrap' },
  greeting: { fontSize: 22, fontWeight: 700, color: 'var(--text-1)', letterSpacing: '-0.4px', marginBottom: 4 },
  subGreeting: { fontSize: 13, color: 'var(--text-3)' },
  headerRight: { display: 'flex', gap: 10, alignItems: 'center', flexShrink: 0 },
  monthPicker: {
    display: 'flex', alignItems: 'center', gap: 4,
    background: 'var(--input-bg)', border: '1px solid var(--border-strong)',
    borderRadius: 10, padding: '6px 8px',
  },
  arrowBtn: { background: 'transparent', border: 'none', cursor: 'pointer', color: 'var(--text-2)', display: 'flex', alignItems: 'center', padding: '2px 4px', borderRadius: 6 },
  monthLabel: { fontSize: 13, fontWeight: 600, color: 'var(--text-1)', minWidth: 72, textAlign: 'center' },
  addBtn: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '9px 18px', borderRadius: 10, border: 'none',
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff', fontWeight: 600, fontSize: 13, cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(99,102,241,0.3)',
  },
  syncBtn: {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '8px 14px', borderRadius: 9,
    background: 'var(--input-bg)', border: '1px solid var(--border-strong)',
    color: 'var(--text-2)', fontWeight: 500, fontSize: 12, cursor: 'pointer',
  },

  plaidBanner: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 20,
    background: 'linear-gradient(135deg, rgba(99,102,241,0.12), rgba(139,92,246,0.08))',
    border: '1px solid rgba(99,102,241,0.25)',
    borderRadius: 16, padding: '20px 24px', marginBottom: 20,
  },
  plaidBannerLeft: { display: 'flex', alignItems: 'center', gap: 16 },
  plaidBannerIcon: {
    width: 44, height: 44, borderRadius: 12, flexShrink: 0,
    background: 'rgba(99,102,241,0.2)', border: '1px solid rgba(99,102,241,0.3)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  plaidBannerTitle: { fontSize: 16, fontWeight: 700, color: 'var(--text-1)', marginBottom: 4, letterSpacing: '-0.2px' },
  plaidBannerSub: { fontSize: 13, color: 'var(--text-2)', maxWidth: 480 },
  warnBanner: {
    display: 'flex', alignItems: 'center', gap: 10,
    background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.25)',
    borderRadius: 12, padding: '12px 16px', marginBottom: 20, color: '#fbbf24', fontSize: 13,
  },
  codeChip: { background: 'var(--border)', padding: '1px 6px', borderRadius: 4, fontFamily: 'ui-monospace, SFMono-Regular, monospace', fontSize: 12 },

  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 20 },
  chartsRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 },
  chartCard: { background: 'var(--surface-1)', border: '1px solid var(--border)', borderRadius: 16, padding: '22px 24px' },
  chartTitle: { fontSize: 13, fontWeight: 600, color: 'var(--text-2)', marginBottom: 16, letterSpacing: '0.02em', textTransform: 'uppercase' },
  legend: { display: 'flex', flexDirection: 'column', gap: 6, marginTop: 12 },
  legendItem: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 13 },
  legendDot: { width: 8, height: 8, borderRadius: '50%', flexShrink: 0 },
  legendName: { color: 'var(--text-2)', flex: 1 },
  legendVal: { color: 'var(--text-2)', fontWeight: 600, fontVariantNumeric: 'tabular-nums' },

  recentCard: { background: 'var(--surface-1)', border: '1px solid var(--border)', borderRadius: 16, padding: '22px 24px', marginBottom: 20 },
  recentHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  viewAllBtn: { background: 'none', border: 'none', color: '#818cf8', fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  recentList: { display: 'flex', flexDirection: 'column', gap: 2 },
  recentRow: { display: 'flex', alignItems: 'center', gap: 12, padding: '10px 4px', borderRadius: 8 },
  txIcon: { width: 36, height: 36, borderRadius: 10, flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  txMeta: { flex: 1, minWidth: 0 },
  txDesc: { display: 'block', fontSize: 14, fontWeight: 500, color: 'var(--text-1)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  txCat: { display: 'block', fontSize: 12, color: 'var(--text-3)', marginTop: 2 },
  txAmt: { fontSize: 14, fontWeight: 700, whiteSpace: 'nowrap', fontVariantNumeric: 'tabular-nums' },

  insightBtn: {
    display: 'inline-flex', alignItems: 'center', gap: 8,
    padding: '12px 22px', borderRadius: 10, border: 'none',
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff', fontWeight: 600, fontSize: 14, cursor: 'pointer',
    boxShadow: '0 4px 16px rgba(99,102,241,0.3)',
  },

  connectEmpty: { background: 'var(--surface-1)', border: '1px solid var(--border)', borderRadius: 18, padding: '56px 32px', textAlign: 'center' },
  connectEmptyIcon: { width: 72, height: 72, borderRadius: 18, margin: '0 auto 20px', background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.25)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  connectEmptyTitle: { fontSize: 22, fontWeight: 700, color: 'var(--text-1)', marginBottom: 10, letterSpacing: '-0.3px' },
  connectEmptySub: { fontSize: 14, color: 'var(--text-2)', maxWidth: 460, margin: '0 auto', lineHeight: 1.6 },
  trustRow: { display: 'flex', justifyContent: 'center', gap: 28, marginTop: 28, flexWrap: 'wrap' },
  trustItem: { fontSize: 12, color: 'var(--text-3)', fontWeight: 500 },
  accountsHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
  itemsGrid: { display: 'flex', flexDirection: 'column', gap: 14 },
  itemCard: { background: 'var(--surface-1)', border: '1px solid var(--border)', borderRadius: 16, padding: 22 },
  itemHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  itemHeaderLeft: { display: 'flex', alignItems: 'center', gap: 14 },
  itemIcon: { width: 40, height: 40, borderRadius: 10, background: 'rgba(99,102,241,0.12)', border: '1px solid rgba(99,102,241,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  itemName: { fontSize: 15, fontWeight: 700, color: 'var(--text-1)', marginBottom: 3 },
  itemMeta: { fontSize: 12, color: 'var(--text-3)', display: 'flex', alignItems: 'center', gap: 5 },
  itemError: { background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)', color: '#fca5a5', fontSize: 12, padding: '8px 12px', borderRadius: 8, marginBottom: 12, display: 'flex', alignItems: 'center', gap: 6 },
  disconnectBtn: { background: 'var(--surface-1)', border: '1px solid var(--border)', color: 'var(--text-3)', borderRadius: 8, cursor: 'pointer', display: 'flex', padding: 8 },
  accountList: { display: 'flex', flexDirection: 'column', gap: 6, borderTop: '1px solid var(--border)', paddingTop: 14 },
  accountRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0' },
  accountLeft: { display: 'flex', alignItems: 'center', gap: 12 },
  accountIcon: { width: 30, height: 30, borderRadius: 8, background: 'var(--input-bg)', color: 'var(--text-2)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  accountName: { fontSize: 14, fontWeight: 500, color: 'var(--text-1)' },
  accountSubtype: { fontSize: 12, color: 'var(--text-3)', marginTop: 2, textTransform: 'capitalize' },
  accountBalance: { fontSize: 15, fontWeight: 700, color: 'var(--text-1)', fontVariantNumeric: 'tabular-nums' },

  overlay: { position: 'fixed', inset: 0, background: 'rgba(7,7,20,0.8)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200, padding: 24 },
  modal: { background: 'var(--surface-2)', border: '1px solid var(--border-strong)', borderRadius: 18, padding: '28px 32px', width: '100%', maxWidth: 520, boxShadow: '0 24px 80px rgba(0,0,0,0.6)' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  modalTitle: { fontSize: 18, fontWeight: 700, color: 'var(--text-1)', letterSpacing: '-0.3px' },
  closeBtn: { background: 'var(--border)', border: '1px solid var(--border-strong)', borderRadius: 8, cursor: 'pointer', color: 'var(--text-2)', display: 'flex', padding: 7 },
  modalForm: { display: 'flex', flexDirection: 'column', gap: 16 },
  formRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 },
  formField: { display: 'flex', flexDirection: 'column', gap: 7 },
  formLabel: { fontSize: 12, fontWeight: 600, color: 'var(--text-2)', textTransform: 'uppercase', letterSpacing: '0.05em' },
  formInput: { padding: '11px 14px', borderRadius: 9, border: '1px solid var(--border-strong)', background: 'var(--input-bg)', color: 'var(--text-1)', fontSize: 14, outline: 'none', transition: 'border-color 0.15s, box-shadow 0.15s', fontFamily: 'inherit' },
  modalActions: { display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 4 },
  cancelBtn: { padding: '10px 18px', borderRadius: 9, border: '1px solid var(--border-strong)', background: 'var(--input-bg)', color: 'var(--text-2)', fontSize: 14, fontWeight: 500, cursor: 'pointer' },
  confirmBtn: { padding: '10px 20px', borderRadius: 9, border: 'none', background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer', boxShadow: '0 4px 14px rgba(99,102,241,0.3)' },
};
